export * from './App/App'
export * from './Navbar/navbar'
export * from './Title/title'
export * from './Work/work'

// export * from './OLD/App/App'
// export * from './OLD/Hero/hero'
// export * from './OLD/Navbar/navbar'
// export * from './OLD/About/about'
// export * from './OLD/Coding/coding'
// export * from './OLD/Photography/photography'