export * from './App/App'
export * from './Navbar/navbar'
export * from './Title/title'
export * from './Work/work'
export * from './About/about'
export * from './Frq/frq'
export * from './Footer/footer'